//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSSFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enlaces
    {
        public long Id { get; set; }
        public string Descripcion { get; set; }
        public string Categorias { get; set; }
        public string link { get; set; }
        public string NotasAdicionales { get; set; }
        public long RSS { get; set; }
    
        public virtual RSS RSS1 { get; set; }
    }
}
