//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSSFeed
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSS
    {
        public RSS()
        {
            this.Enlaces = new HashSet<Enlaces>();
        }
    
        public long id { get; set; }
        public string nombre { get; set; }
        public string link { get; set; }
        public string Palabras { get; set; }
        public string operador { get; set; }
    
        public virtual ICollection<Enlaces> Enlaces { get; set; }
    }
}
